# Generated by Django 6.0.3 on 2026-03-24 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_listing_title', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('DELETE_LISTING', 'Delete Listing'), ('RESTORE_LISTING', 'Restore Listing')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_against', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
