# Generated by Django 6.0.3 on 2026-04-07 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_moderationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='banrecord',
            name='banned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='action',
            field=models.CharField(choices=[('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('DELETE_LISTING', 'Delete Listing'), ('RESTORE_LISTING', 'Restore Listing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_targets', to=settings.AUTH_USER_MODEL),
        ),
    ]
