# Generated by Django 6.0.3 on 2026-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_sold_alter_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='approval_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
