# Generated by Django 6.0.3 on 2026-03-29 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('listings', '0002_remove_listing_deleted_on_listing_bathrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_note', models.TextField(blank=True)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('RejectedBySeller', 'Rejected By Seller'), ('AcceptedBySeller', 'Accepted By Seller'), ('RejectedByBuyer', 'Rejected By Buyer'), ('AcceptedByBuyer', 'Accepted By Buyer'), ('CounterSent', 'Counter Sent'), ('Deleted', 'Deleted')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
