# Generated by Django 6.0.3 on 2026-03-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_buyerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerapplication',
            name='bank_statement_1',
            field=models.FileField(blank=True, null=True, upload_to='applications/bank_statements/'),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='bank_statement_2',
            field=models.FileField(blank=True, null=True, upload_to='applications/bank_statements/'),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='bank_statement_3',
            field=models.FileField(blank=True, null=True, upload_to='applications/bank_statements/'),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='gov_id',
            field=models.FileField(blank=True, null=True, upload_to='applications/gov_ids/'),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buyerapplication',
            name='mortgage_pre_approval',
            field=models.FileField(blank=True, null=True, upload_to='applications/mortgage_docs/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interactions.buyerapplication'),
        ),
        migrations.AlterField(
            model_name='buyerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('RejectedBySeller', 'Rejected By Seller'), ('AcceptedBySeller', 'Accepted By Seller'), ('RejectedByBuyer', 'Rejected By Buyer'), ('AcceptedByBuyer', 'Accepted By Buyer'), ('CounterSent', 'Counter Sent'), ('Deleted', 'Deleted'), ('Paid', 'Paid')], default='Pending', max_length=30),
        ),
    ]
